id: ID5DDD534
ocr_import_info:
  timestamp: '2023-09-27T14:27:17.642259+00:00'
  batch_id: batch-a4b7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 14:40:27.509611+00:00
last_modified: 2023-09-27 14:40:27.509617+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1117
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1117
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་དགོངས་འགྲེལ་གྱི་བསྟན་བཅོས་ཐུབ་བསྟན་ནོར་བུའི་གཏེར་མཛོད་དུས་གསུམ་རྒྱལ་བའི་བཞེད་དོན་ཀུན་གསལ།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9379063878747439
  ocr_word_median_confidence_index: 0.9886742
bases:
  I1NLM1117_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1117_001
      total_pages: 558
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1117_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9886742
      ocr_word_mean_confidence_index: 0.9379063878747439
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
